apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  labels:
    app: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - name: application
      port: 80
      targetPort: 8080
      nodePort: 30007
    - name: http
      port: 8080
      targetPort: 8080